### ISSUE TITLE
Research KeystoneJS

### ISSUE THREAD

**Issue by MattRiina** [Nicholas-Nazario/twitterLens#10]
KeystoneJS will be used as the main framework of the project, so research must be done on how to use it to fit our needs

**Comment by Nicholas-Nazario** [comment]
I worked through the KeystoneJS tutorials and set up an initial skeleton website so that the rest of the group would be able to test their code in a web application setting. I linked the website to a basic MongoDB instance, for which Matthew Solomon will be creating the schema. Additionally, I've documented and/or provided links to documentation on how to setup KeystoneJS, MongoDB, and the TwitterLens web app on everyone's systems
