### ISSUE TITLE
Obtain Stock API Key

### ISSUE THREAD

**Issue by MattRiina** [Nicholas-Nazario/twitterLens#3]
We must obtain a stock API key to pull stock data to the project

**Comment by Daniel-Peladeau** [comment]
Stock API Key from Alpha Vantage was secured for the test environment. This key is now located in the Relevant Links sheet under the Documentation folder in the Git Push Git Paid Google Drive. It is also currently being used in the test environment, so more keys will have to be made in the future for the full website in order to remain under the data cap of 500 pulls per day.
