### ISSUE TITLE
Convert Stock Ticker to Twitter Handle and Company Name

### ISSUE THREAD

**Issue by Nicholas-Nazario** [Nicholas-Nazario/twitterLens#46]
Design to integrate with Andy's searchable dropdown:
-The Dropdown will provide stock tickers, you need to use those and return company twitter handles and the company name
- Talk to Andy about how to integrate the two

**Comment by Daniel-Peladeau** [comment]
@Matthew-Solomon @emanua Has this been completed through the addition of the Dropdown search functionality?

**Comment by emanua** [comment]
Stock ticker and company name is complete, which is what I believe the original intention of this was supposed to be as we discussed it. We could further integrate this by displaying the company name and ticker after selection (only one will be shown in dropdown currently), and by searching company name in twitter rather than just ticker. We can also add exact twitter handles to the company options json file, but that will require finding each one individually and is not feasible or necessary unless we want to give links to follow them.
